### ISSUE TITLE
Fix default devfs_ruleset

### ISSUE THREAD

**Issue by nirvdrum** [tprelog/iocage-homeassistant#1]
I don't entirely understand how devfs rulesets interact with iocage, but I ran into [the same issue](https://forums.freenas.org/index.php?threads/usb-device-no-longer-shows-in-iocage-jail-after-freenas-11-2-rc2-update.71301/) as @tprelog, which prevented my Aeotec Z-Wave USB stick from being accessible. There are two solutions put forth in that thread. The first is to change the devfs_ruleset from `4` to `3`. I don't know iocage well enough to know if that can be done at jail creation time or if it must be modified afterwards. The second solution was to define the ruleset so the correct entries appear.

This might just be something that has to be addressed in the README, although I'm really hoping it can work better "out of the box".

**Comment by tprelog** [comment]
@nirvdrum 

You can set the devfs_ruleset at creation time by simply adding `devfs_ruleset=3` to the jail properties.
I think this will be the only way to provide an "out of the box" working z-wave (or zigbee) USB stick.
For example to create the homeassistant 'standard-jail' with _devfs_ruleset=3_

    sudo iocage create -r 11.2-RELEASE boot=on dhcp=on bpf=yes vnet=on devfs_ruleset=3 -p /tmp/pkglist.json -n homeassistant

If you have already created your jail you can set `devfs_ruleset=3` and reboot to the jail quickly from the command line.
    
    sudo iocage set devfs_ruleset=3 homeassistant && sudo iocage homeassistant restart
----

While I would prefer the second option to redefine rule sets, this actually requires changing the devfs_ruleset on the host FreeNAS system itself. At this time my script can't modify the host system beyond creating the jail and what's inside. 

That being said I have tried. I can correctly modify the host system ruleset but these changes however are continually lost upon rebooting either the jail or FreeNAS. Honestly I'm not a FreeNAS (or FreeBSD) expert but to my knowledge, these changes would need to made in FreeNAS GUI. It's my understanding, FreeNAS setting applied in the GUI are saved in a 'settings database' and basically every time you reboot, FreeNAS boots a default clean image and applies (or overlays) you're settings from the database. Changes made from the command line (read my script) are not saved to this 'settings database' and therefore lost upon reboot.

I think just setting `devfs_ruleset=3` works because it already exists on the FreeNAS host and based on viewing `/etc/defaults/devfs.rules` seems to be intended for a login user. This exposes much more of the `/dev/` tree which fortunately includes 'cua*' devices even though not explicitly mentioned. Because `devfs_ruleset=3` exposes our z-wave without the need for a custom entry (which would need saved to the FreeNAS 'setting database') we can set the jail to this and have zwave available through reboots.

I do feel setting `devfs_ruleset=3` seems more like a quick work around for an "out of the box"  zwave experience and it is currently how I myself have re-exposed my z-wave to homeassistant. Unfortunately I think having a more advanced configuration beyond `devfs_ruleset=3` will require additional setup beyond what I am capable with this simple bash install  script.
