### ISSUE TITLE
Update brakes plugin

### ISSUE THREAD

**Issue by basnagel** [tprelog/iocage-homeassistant#22]
I tried a update off the plugin because sometimes you add dependencies.

Only this time it broke the plugin, the website was not found. 
In the shell homeassistant was running when I checked the status.
Unsure what happend exactly.

I am running the Freenas 11.3 stable train.
0.112.2 of HA was installed at plugin update.
tried again with 0.112.5 installed, same result

(A snapshot rollback fixed my install.)

**Comment by tprelog** [comment]
hi @basnagel 
sorry for the trouble. :thinking: I'm not sure what would cause this...

>Only this time it broke the plugin, the website was not found.
>In the shell homeassistant was running when I checked the status.

The good news is, I'm working a on complete refactor of this plugin that should ( hopefully ) be ready in the next day or two. The current install script was originally written over years ago and has just been hacked on since. ( throw this in here, add a work around there - types of things ) -- Bottom line, it makes it through the install, but it's a mess and already getting unmanageable from an _after the fact point_ of view. Meaning there is to much of the past I'm trying to clean up and account for during a Plugin Update and I currently have no good way to it. Because I have said ( and I think is critical for long term success of this plugin ) you can treat this plugin like a manual jail -- I can not just automatically handle these changes the way one might expect

Individually, each case of _If this then do that_, ranges from simple, to few a easy steps -- The problem is writing all the logic to figure out each case ( _in a simple script_ ) -- Case in point, you likely found something I missed.

Anyways, with everything refactored, this plugin will use `$rcvars` as much as possible. These will be set during during installation and be relied upon to ( hopefully ) handle plugin updates correctly -- more correctly said, this will preserve your existing rc config if one of the defaults changes. This is be critical factor that will allow this plugin to be successfully upgrade to the 12.1-RELEASE on TrueNAS Core 12 as some defaults are changing to be *BSD like and switch the default username from `hass` to `homeassistant`.

At some point later, I suspect I'll back-port the new defaults to FreeNAS but they will only be applied during a clean install. I plan to have a path for FreeNAS to manually switch to these new defaults ( or any other setup ) with minimal effort. You'll also be able to upgrade the python version and rebuild the virtualenv in a matter of two or three steps. Bottom line is, as long as your configuration is intact, it's going to be almost impossible to break this plugin, in a way that can not be recovered from. Plus we always have snapshots to rely on as second line of defense

( even when you do something stupid like `rm -rf /usr/local/share` ) -- Yea -- BIG oops but I was able to recover without needing to rollback a snapshot!

If you don't mind, please wait a few days before you try again. I'll let you know when this update make it's to the 11.3-RELEASE. I'm trying to make this next update as clean as possible but I'm not expecting it to not be perfect. It should at least, be easier to resolve any issues

**Comment by tprelog** [comment]
https://github.com/tprelog/iocage-homeassistant/pull/23

**Comment by tprelog** [comment]
[For real this time](https://github.com/tprelog/iocage-homeassistant/pull/25) - it's a big one - Hopefully I managed to keep any potential breakage to corner cases.

**Comment by tprelog** [comment]
@basnagel - go head and give it another try to Plugin --> UPDATE

If you still have issues -- you can check the logs from the console
```
iocage console $jail
# Press '0' to exit the menu
service homeassistant logs
```

[There are a couple other commands to view the logs also](https://github.com/tprelog/iocage-homeassistant/wiki/autostart-and-rc-service#view-the-log-file) -- nothing extensive but I hope they're still helpful

**Comment by gandl** [comment]
Hi,
i just upgraded as well and have no more access to the web interface, i get the following error within the logs:
ERROR (MainThread) [homeassistant.auth.providers] Unable to load auth provider homeassistant: Shared object "libffi.so.6" not found, required by "_cffi_backend.so"
ERROR (MainThread) [homeassistant.bootstrap] Home Assistant core failed to initialize. Further initialization aborted
WARNING (MainThread) [homeassistant.bootstrap] Unable to set up core integrations. Activating safe mode
ERROR (MainThread) [homeassistant.auth.providers] Unable to load auth provider homeassistant: Shared object "libffi.so.6" not found, required by "_cffi_backend.so"
ERROR (MainThread) [homeassistant.bootstrap] Home Assistant core failed to initialize. Further initialization aborted

Can i try something else or do you need more information?
"Status" in the menu says that its running.

best regards

**Comment by tprelog** [comment]
Hi @gandl 
 User odinbolt [has discovered this seems to be caused by an update to Python](https://community.home-assistant.io/t/home-assistant-core-freenas-truenas-core-community-plugin/170542/129?u=troy). As I mentioned to him, I have seen this issue in some other plugins as well. I have not been able to track a reason why this Python update is effecting Home Assistant this way. Clean installs with the updated Python do not seem to be effected. 

The easy fix right now is to [recreate the virtualenv](https://github.com/tprelog/iocage-homeassistant/wiki/autostart-and-rc-service#reinstall-home-assistant-core) -- I'm sorry I do not have a better solution to offer at this time. You may try to make the best of this situation by also upgrading to Python 3.8 ( which also requires recreating the venv )

```
iocage console $jail
pkg install python38 py38-sqlite3
sysrc homeassistant_python=/usr/local/bin/python3.8
service homeassistant reinstall
```

**Comment by gandl** [comment]
It worked.
Thank you very much for your help and advice. 
And for your work on this plugin.

best regards and be well.
