### ISSUE TITLE
Installing VSCode Plugin

### ISSUE THREAD

**Issue by fahadshery** [tprelog/iocage-homeassistant#34]
Hi,

Just getting started with HA so it may be a stupid question.
I have seen countless YouTube vids where they are using VSCode to edit configuration.yml files etc. How do I install it because I can't see Hass.io like in the vids?
I bought a Lidl Zigbee Gateway and attached my Smart bulbs and using Smart Life app to control. What do I need to do to set it up in HA?

I also installed Plex using: Configurations -> Integrations -> Add INTIGRATION
Then registered using the plex creds and now Plex shows up on the home page (Overview) and shows up if anything is being played so I am a happy bunny there 👍 

Thanking you a million times for your efforts :)

**Comment by tprelog** [comment]
> VSCode to edit configuration.yml files etc. How do I install it because I can't see Hass.io like in the vids?

You have already found one problem, as [you've already relied requesting FreeBSD support.](https://github.com/microsoft/vscode-remote-release/issues/727#issuecomment-741949115)

With out the remote editing stuff, I think we are out of luck getting that full VS-Code addon experience. The Supervisor and addons are all Docker containers and there is no working Docker on FreeBSD. Without Docker, there is no chance for the Supervisor and we can not have addons without the Supervisor.

So, to side track a minute over to the issue of this plugin's future. Here is a perfect example of why switching to SCALE is an advantage... Scale is built on Debian and includes Docker. To be clear, you would still need the Supervisor in order to have addons but remember addons are just Docker containers. This means on Scale, you could install the VS-Code Docker container yourself and manually configure the same experience as provided by the addon. In a general sense, saying it's an "addon" means pre-configured Docker container managed by the Supervisor. I hope that helps a little.

And back to question...

You can still use VS-Code that installed on your Mac, just not like the addon does. Instead[, you should create a SMB share for the configuration](https://github.com/tprelog/iocage-homeassistant/wiki/smb_share) and just open/edit the files from your Mac

You can still use the [Home Assistant Config Helper, VS-Code Extension](https://marketplace.visualstudio.com/items?itemName=keesschollaart.vscode-home-assistant) as well, however I found I needed to mount the SMB share as local storage for this to work. Using Windows, this is done by mapping a network drive.

I use Linux and accomplished this by creating `cifs` mount in the `/etc/fstab` file on my desktop computer (where I run VS-Code from) I'm not sure how you mount a network drive on a Mac but I imagine there is a way.


> I bought a Lidl Zigbee Gateway and attached my Smart bulbs and using Smart Life app to control. What do I need to do to set it up in HA?

I'm gonna refer you to the general [Home Assistant Community](https://community.home-assistant.io/) and [official documentation for integrations](https://www.home-assistant.io/integrations) for that. Typically, setting up an integration is the same in Home Assistant. I mean to say, integration are not addons. Integrations are provided in the same manner across the different Home Assistant installation methods.

**Comment by adorobis** [comment]
The other option is to connect to TrueNAS and to the HA jail via SSH. For file editing the best is WinSCP which connects via SSH and allows for direct file editing using whatever code editor you like (in my case it is Notepad++). With proper configuration of SSL for the TrueNAS you can also connect to it from anywhere, alternatively you can set-up a VPN which would be even more secure.

**Comment by tprelog** [comment]
Just a side note on @adorobis comment. He is correct, I've also used ssh to edit my config in the past, just be aware, you'll need to keep your permissions in check on your own if you connect with ssh.

I have VPN access to my local network. I can still edit files in the SMB share when I connect using the VPN - They both work, I just find it's easier to use the SMB share.

That said,  [SSH FS is an other great extension for VS-Code](https://github.com/SchoofsKelvin/vscode-sshfs#ssh-fs) I have used previously used. In the past I have used this to connect directly to my TrueNAS server and I've also connected directly to the jail with it but the setup was not straight forward when It comes to keeping permissions in check.

**Comment by fahadshery** [comment]
Wow! Great response from you. Thank you!!

First of all, I tried your SSH FS extension and works a treat. I was able to login using my ssh private key and open the configuration.yml file. However, couldn't save it because I logged in as a jail user which I could add to home assistant group I guess?

@tprelog you've done a great community service by managing this plugin. I think it will be helpful to expand the WiKi pages to cover the 'Basic' topics such as 'Installing a Weather Card using Hacs'. I am struggling to get my home address weather information even without the HACS and I have no idea where to edit or which file is it using to pull the weather information.

To expand on it: when I ran the home assistant for the first time, it asked for the address which it failed to auto detect. Then I moved the pin to the home address but there is no weather information still. Just showing:
<img width="872" alt="Screenshot 2020-12-11 at 17 33 51" src="https://user-images.githubusercontent.com/7301267/101935599-3d74bc00-3bd7-11eb-957a-c8daf2ba1768.png">

it is also showing hacs as pending?? not sure what it means.

After googling for Lidl gateway and lights, someone mentioned to install deCONZ. When I install it via Integrations, it asks for an IP address (not sure which though) when I supplied my HA jail IP address it asks to open the deCONZ device settings. But I have no deCONZ device?

Finally, wth is Lovelace. 

So these little things basic information is missing from online tutorials and the wiki pages.

thanks again for your response.

cheers!

**Comment by tprelog** [comment]
> I tried your SSH FS extension and works a treat.

Thanks but I just made a suggestion. That is _not mine_ and _I have no involvement_ there.

> First of all, I tried your SSH FS extension and works a treat. I was able to login using my ssh private key and open the configuration.yml file. However, couldn't save it because I logged in as a jail user which I could add to home assistant group I guess?

Yes add your user to the homeassistant group inside the jail. Again, be careful here - You going to take ownership of any files you edit. You'll need to make sure the `homeassistant` group has RW access to files the Home Assistant service needs to interact with, otherwise it will fail with errors.

> I think it will be helpful to expand the WiKi pages to cover the 'Basic' topics such as 'Installing a Weather Card using Hacs'.

Please have a look a the [HACS documentation](https://hacs.xyz/docs/basic/getting_started). Everything is already covered there. HACS is a custom integration for Home Assistant and it use is the same across all installation methods, there are no special consideration because you're using this plugin.

I will say though, your HACS sensor looks fine. Its says `0` pending updates because there are no updates available for HACS or anything you have install using it. When there is an update available for something, it will change. As you see here I have 1 update pending.

![image](https://user-images.githubusercontent.com/35702532/101942111-01c9fa00-3bb7-11eb-9803-b68b6e8f1277.png)

> I have no idea where to edit or which file is it using to pull the weather information.

That's odd, I've never seen the location fail before. The weather is based on that setting. 

You can still manually configure location information using `yaml`
https://www.home-assistant.io/docs/configuration/basic/

> After googling for Lidl gateway and lights, someone mentioned to install deCONZ.

I'm sorry, I don't use Zigbee so I'm unable to help with configuring deCONZ. I'm pretty sure this is something you would run in a separate jail and the ip address should point to your deCONZ server. The only Zigbee that is built into Home Assistant is [ZHA](https://www.home-assistant.io/integrations/zha/)
