### ISSUE TITLE
Possible doubly nested folder name in post install

### ISSUE THREAD

**Issue by dasfdlinux** [tprelog/iocage-homeassistant#35]
I recently found Home Assistant and was looking into ways to install an instance on TrueNAS when I saw your plugin. I just started browsing your repo to see how you create a plugin and what your plugin does when I saw the following:

https://github.com/tprelog/iocage-homeassistant/blob/8276ca3c8f3b8d2ea3103b51acd7c3f1fd12d9c5/post_install.sh#L11-L13

Are you purposely creating a doubly nested folder? It looks like you would end up with a path `service_config = "/home/homeassistant/homeassistant"`. It seems like it might better serve if it looked more like `service_config="${service_home}/config"`.

I admit I've only spent a little time reading through these files, so if I've missed something obvious please excuse my oversight.

**Comment by dasfdlinux** [comment]
Also, just as a head's up it looks like some of the code expects this to be a hidden folder (prefaced with a dot) and some doesn't.
https://github.com/tprelog/iocage-homeassistant/blob/8276ca3c8f3b8d2ea3103b51acd7c3f1fd12d9c5/overlay/usr/local/etc/rc.d/homeassistant#L68
https://github.com/tprelog/iocage-homeassistant/blob/8276ca3c8f3b8d2ea3103b51acd7c3f1fd12d9c5/overlay/root/bin/menu_service#L31

**Comment by tprelog** [comment]
Yes that is intentional.  There are a few reasons.

1. This plugin also includes an option to install the Hass-Configurator, more commonly know around HA as :wrench: File Editor
2. There is also an option to install AppDaemon, which includes HaDashboard

The additional services will also follow  the `service_config="${service_home}/${service_name}" ` standard.

>It looks like you would end up with a path service_config = "/home/homeassistant/homeassistant"

It just happens to be that way in this case because the username matches the service name.

I'm not really a fan of it either. This is the main reason I tried for long to hold on to the old `hass` username. I liked `/home/hass/homeassistant` sooo much better.

The layout will likely make more sense after some time has passed. - This is my `$service_home` directory after three years.
You can see the there are separate configuration directories for each service as well as other files and folders I wish to keep separate from the actual service configuration

![image](https://user-images.githubusercontent.com/35702532/102374958-ef253b80-3f8f-11eb-86fd-d025d364e844.png)

>Also, just as a head's up it looks like some of the code expects this to be a hidden folder (prefaced with a dot) and some doesn't.

This plugin can be mostly configured using `sysrc` -- The default value I included in the [`rc.d/homeassistant`](https://github.com/tprelog/iocage-homeassistant/blob/8276ca3c8f3b8d2ea3103b51acd7c3f1fd12d9c5/overlay/usr/local/etc/rc.d/homeassistant#L68), is the default location the Home Assistant would create the configuration if the `--config` option is not set.

Since we are using a jail, I override that value using `sysrc` during the installation of the services. For Home Assistant, you can see that here (I see no value in this folder being hidden inside the jail)
https://github.com/tprelog/iocage-homeassistant/blob/8276ca3c8f3b8d2ea3103b51acd7c3f1fd12d9c5/post_install.sh#L26

And for the other services, that happens here
https://github.com/tprelog/iocage-homeassistant/blob/8276ca3c8f3b8d2ea3103b51acd7c3f1fd12d9c5/overlay/root/bin/menu_service#L48

---

I still need to improve documentation around the `rc/homeassistant` service script. There is a temporary wiki page I have started some notes on... This is not even a draft of an outline at this point but it does list all the rcvars for Home Assistant, that can be configured using `sysrc`

https://github.com/tprelog/iocage-homeassistant/wiki/temp_rcd_homeassistant

**Comment by tprelog** [comment]
I should add, all the services can be configured using `sysrc` however since Home Assistant is focus here, it is the most complete rc service script.

I wanted the rc.d/homeassistant to be able stand on it's own, without using this plugin.

This does not cover all the rcvars listed on the wiki page, but provides any example of using `sysrc` to configure the Home Assistant service outside of this plugin.

https://github.com/tprelog/iocage-homeassistant/wiki/autostart-and-rc-service

AppDaemon and the Configurator are still included in the plugin because they are negligible maintenance burden. I assume most people will be jumping over to SCALE next year, and running Home Assistant using Docker instead. If this plugin survives, I may look into expanding the other service scripts as well.

**Comment by dasfdlinux** [comment]
> It just happens to be that way in this case because the username matches the service name.

Actually, won't it always end up that way since
https://github.com/tprelog/iocage-homeassistant/blob/8276ca3c8f3b8d2ea3103b51acd7c3f1fd12d9c5/post_install.sh#L11-L13
expands to `service_config = "/home/${service_name}/${service_name}"`?

Thanks for explaining sysrc portion - I haven't dealt with that before.

**Comment by tprelog** [comment]
> Actually, won't it always end up that way since

It may not be clear to see. Let try to explain like this...

```
service_home="/home/${service_name}"
service_config="${service_home}/${service_name}" 
```

The default user created by this plugin is `homeassistant`, which also match the name of the primary service. So we end up with
```bash
service_config = "/home/homeassistant/homeassistant"
```

additional services provided by this plugin are run by the same `homeassistant` user - regardless of what you see set as default in the respective rc service scripts. As mentioned, this is done by setting rcvars using`sysrc`.

The actual location for configuration of additional service, in this plugin, are the following
```bash
## Appdaemon
service_config = "/home/homeassistant/appdaemon"

## Configurator
service_config = "/home/homeassistant/configurator"
```

**Comment by dasfdlinux** [comment]
Okay, I see that better now. I was picturing someone creating the plugin with a username like `johnsmith` and ending up with a setup such as 
```
## Home Assistant
service_config = "/home/johnsmith/johnsmith"
## Appdaemon
service_config = "/home/johnsmith/appdaemon"
## Configurator
service_config = "/home/johnsmith/configurator"
```
But I see that using a default name of `homeassistant` would make more sense.

Thanks for taking the time to talk it through.

**Comment by tprelog** [comment]
> Okay, I see that better now. I was picturing someone creating the plugin with a username like `johnsmith` and ending up with a setup such as

Yes, it should work that way as well,... That was idea of allowing configuration using `sysrc`  -- Although it not a stream lined solution at this time

It is possible (with some extra work) to setup your own user and configuration layout using `sysrc`, for example

```
sysrc homeassistant_user=johnsmith
sysrc_homeassistant_config_dir=/config
```

It also possible to load the values from a file. If this plugin survives, I have some ideas how advanced users could possibly store there own plugin settings using a file inside the `service_home="/home/${service_name}"` directory. (ideally $service_home is located on a separate dataset)
